import { User } from './types';

export const MOCK_USERS: User[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    status: 'active',
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    status: 'active',
  },
  {
    id: '3',
    name: 'Bob Johnson',
    email: 'bob.johnson@example.com',
    status: 'inactive',
  },
  {
    id: '4',
    name: 'Alice Brown',
    email: 'alice.brown@example.com',
    status: 'active',
  },
  {
    id: '5',
    name: 'Charlie Wilson',
    email: 'charlie.wilson@example.com',
    status: 'inactive',
  },
  {
    id: '6',
    name: 'Emma Davis',
    email: 'emma.davis@example.com',
    status: 'active',
  },
  {
    id: '7',
    name: 'Frank Miller',
    email: 'frank.miller@example.com',
    status: 'inactive',
  },
  {
    id: '8',
    name: 'Grace Lee',
    email: 'grace.lee@example.com',
    status: 'active',
  },
  {
    id: '9',
    name: 'Henry Taylor',
    email: 'henry.taylor@example.com',
    status: 'inactive',
  },
  {
    id: '10',
    name: 'Ivy Anderson',
    email: 'ivy.anderson@example.com',
    status: 'active',
  },
  {
    id: '11',
    name: 'Jack White',
    email: 'jack.white@example.com',
    status: 'active',
  },
  {
    id: '12',
    name: 'Kelly Martinez',
    email: 'kelly.martinez@example.com',
    status: 'inactive',
  },
  {
    id: '13',
    name: 'Liam Garcia',
    email: 'liam.garcia@example.com',
    status: 'active',
  },
  {
    id: '14',
    name: 'Mia Robinson',
    email: 'mia.robinson@example.com',
    status: 'inactive',
  },
  {
    id: '15',
    name: 'Noah Clark',
    email: 'noah.clark@example.com',
    status: 'active',
  },
  {
    id: '16',
    name: 'Olivia Rodriguez',
    email: 'olivia.rodriguez@example.com',
    status: 'active',
  },
  {
    id: '17',
    name: 'Peter Lewis',
    email: 'peter.lewis@example.com',
    status: 'inactive',
  },
  {
    id: '18',
    name: 'Quinn Walker',
    email: 'quinn.walker@example.com',
    status: 'active',
  },
  {
    id: '19',
    name: 'Rachel Hall',
    email: 'rachel.hall@example.com',
    status: 'inactive',
  },
  {
    id: '20',
    name: 'Samuel Young',
    email: 'samuel.young@example.com',
    status: 'active',
  },
  {
    id: '21',
    name: 'Tina Allen',
    email: 'tina.allen@example.com',
    status: 'active',
  },
  {
    id: '22',
    name: 'Ulysses King',
    email: 'ulysses.king@example.com',
    status: 'inactive',
  },
  {
    id: '23',
    name: 'Victoria Scott',
    email: 'victoria.scott@example.com',
    status: 'active',
  },
  {
    id: '24',
    name: 'William Green',
    email: 'william.green@example.com',
    status: 'inactive',
  },
  {
    id: '25',
    name: 'Xena Wright',
    email: 'xena.wright@example.com',
    status: 'active',
  },
];
